name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            glob: ./out/make/deb/x64/*.deb
          - os: windows-latest
            glob: ./out/make/squirrel.windows/x64/*.exe
          - os: macos-latest
            glob: ./out/make/zip/darwin/x64/

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: list files
      run: ls ${{ matrix.glob }}
